# Generated by Django 5.2.4 on 2025-07-24 14:27

import datetime
import django.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('97e8757e-cca6-496d-8b45-fa8c98101ea6'))),
                ('label', models.CharField(max_length=200, verbose_name='Label')),
                ('legal_status', models.CharField(choices=[('Asso', 'Association'), ('Individual', 'Individual company')], verbose_name=django.db.models.fields.CharField)),
                ('repository_code', models.CharField(max_length=20, verbose_name='repository_code')),
                ('street_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Street number')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Street')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('municipality', models.CharField(max_length=200, verbose_name='Municipality')),
                ('inkind_donation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='In-kind Donation')),
                ('inkind_donation_description', models.TextField(blank=True, default='', max_length=500)),
                ('cash_donation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cash Donation')),
                ('cash_payment_type', models.CharField(blank=True, choices=[('Cash', 'Cahs'), ('Cheque', 'Cheque'), ('Bank transfer', 'Bank transfer'), ('Other', 'Other')], null=True)),
                ('date_start', models.DateField(default=datetime.datetime(2025, 7, 24, 14, 27, 34, 536237))),
                ('end_date', models.DateField(default=datetime.datetime(2025, 7, 24, 14, 27, 34, 536253))),
                ('export_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
