# Generated by Django 5.2.4 on 2025-07-30 07:12

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyLegalForms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=4, unique=True, verbose_name="Label"),
                ),
                (
                    "label",
                    models.CharField(max_length=200, unique=True, verbose_name="Label"),
                ),
            ],
            options={
                "verbose_name": "Legal form",
                "verbose_name_plural": "Legal forms",
            },
        ),
        migrations.CreateModel(
            name="Companies",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("21ba5bd6-d2a6-49f6-b35b-5a2f30dacd20"),
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=200, verbose_name="Label")),
                ("email", models.EmailField(max_length=254)),
                (
                    "repository_code",
                    models.CharField(max_length=20, verbose_name="Repository code"),
                ),
                (
                    "additional_address",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Additional address",
                    ),
                ),
                (
                    "street_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Street number",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Street"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Postal code"),
                ),
                (
                    "municipality",
                    models.CharField(max_length=200, verbose_name="Municipality"),
                ),
                (
                    "order",
                    models.IntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Order number",
                    ),
                ),
                (
                    "inkind_donation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="In-kind Donation",
                    ),
                ),
                (
                    "inkind_donation_description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="In-kind Donation description",
                    ),
                ),
                (
                    "cash_donation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Cash Donation",
                    ),
                ),
                (
                    "cash_payment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Cash", "Cash"),
                            ("Cheque", "Cheque"),
                            ("Bank transfer", "Bank transfer"),
                            ("Other", "Other"),
                        ],
                        null=True,
                        verbose_name="Cash payment type",
                    ),
                ),
                (
                    "date_start",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date initiale du don",
                    ),
                ),
                (
                    "date_end",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                ("valid", models.BooleanField(default=False, verbose_name="Valide")),
                (
                    "legal_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cerfa_filler.companylegalforms",
                        verbose_name="Legal status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="BeneficiaryOrganization",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("21ba5bd6-d2a6-49f6-b35b-5a2f30dacd20"),
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=200, verbose_name="Label")),
                ("email", models.EmailField(max_length=254)),
                (
                    "repository_code",
                    models.CharField(max_length=20, verbose_name="Repository code"),
                ),
                (
                    "additional_address",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Additional address",
                    ),
                ),
                (
                    "street_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Street number",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Street"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Postal code"),
                ),
                (
                    "municipality",
                    models.CharField(max_length=200, verbose_name="Municipality"),
                ),
                (
                    "object_description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Object"
                    ),
                ),
                (
                    "legal_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cerfa_filler.companylegalforms",
                        verbose_name="Legal status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beneficiary organization",
                "verbose_name_plural": "Beneficiary organization",
            },
        ),
    ]
