# Generated by Django 5.2.4 on 2025-07-30 07:58

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cerfa_filler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companies",
            name="valid",
        ),
        migrations.AddField(
            model_name="companies",
            name="valid_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Validation date"
            ),
        ),
        migrations.AlterField(
            model_name="beneficiaryorganization",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("04df5a18-545b-43c4-8c5e-220477aa42ae"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="date_end",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="companies",
            name="date_start",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Initial donation date"
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("04df5a18-545b-43c4-8c5e-220477aa42ae"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
