# Generated by Django 5.2.4 on 2025-07-28 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerfa_filler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='order',
            field=models.IntegerField(blank=True, editable=False, max_length=50, null=True, verbose_name='Order number'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='cash_payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank transfer', 'Bank transfer'), ('Other', 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8a60d33c-53e4-40d2-8b70-bf0ae7b87fbc'), primary_key=True, serialize=False, unique=True),
        ),
    ]
