# Generated by Django 5.2.4 on 2025-07-30 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cerfa_filler", "0002_remove_companies_valid_companies_valid_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companylegalforms",
            options={
                "ordering": ("label",),
                "verbose_name": "Legal form",
                "verbose_name_plural": "Legal forms",
            },
        ),
        migrations.AddField(
            model_name="beneficiaryorganization",
            name="sign_file",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Sign image file"
            ),
        ),
    ]
