# Generated by Django 5.2.4 on 2025-07-28 15:03

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerfa_filler', '0002_companies_order_alter_companies_cash_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('65dc30e7-d39c-446a-a76d-ffb4100d6576'), primary_key=True, serialize=False, unique=True),
        ),
    ]
