# Generated by Django 5.2.4 on 2025-07-29 08:54

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerfa_filler', '0003_alter_companies_end_date_alter_companies_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='companies',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='export_date',
        ),
        migrations.AddField(
            model_name='companies',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='companies',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Valide'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='cash_payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank transfer', 'Bank transfer'), ('Other', 'Other')], null=True, verbose_name='Cash payment type'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date initiale du don'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='inkind_donation_description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='In-kind Donation description'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='repository_code',
            field=models.CharField(max_length=20, verbose_name='Repository code'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('829591f2-d517-4186-a63b-0a0bb42e0caf'), primary_key=True, serialize=False, unique=True),
        ),
    ]
