# Generated by Django 5.2.4 on 2025-07-30 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cerfa_filler", "0003_alter_companylegalforms_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companies",
            options={
                "permissions": [
                    ("change_validation", "Can change the validation status")
                ],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
