# Generated by Django 5.2.4 on 2025-07-30 10:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cerfa_filler", "0004_alter_companies_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiaryorganization",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
