# Generated by Django 5.2.4 on 2025-07-29 10:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerfa_filler', '0004_alter_companies_options_remove_companies_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='email',
            field=models.EmailField(default='test@lpo.fr', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companies',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('abc17e4b-94bf-48b2-85da-e01c53383ea2'), primary_key=True, serialize=False, unique=True),
        ),
    ]
