# Generated by Django 5.2.4 on 2025-07-29 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerfa_filler', '0005_companies_email_alter_companies_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryOrganization',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('d8de3789-b505-42d9-8a37-4f375abc31c9'), primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=200, verbose_name='Label')),
                ('email', models.EmailField(max_length=254)),
                ('legal_status', models.CharField(choices=[('Asso', 'Association'), ('Individual', 'Individual company')], verbose_name='Legal status')),
                ('repository_code', models.CharField(max_length=20, verbose_name='Repository code')),
                ('street_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Street number')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Street')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('municipality', models.CharField(max_length=200, verbose_name='Municipality')),
            ],
            options={
                'verbose_name': 'Beneficiary organization',
                'verbose_name_plural': 'Beneficiary organization',
            },
        ),
        migrations.AlterField(
            model_name='companies',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d8de3789-b505-42d9-8a37-4f375abc31c9'), primary_key=True, serialize=False, unique=True),
        ),
    ]
