# Generated by Django 5.2.4 on 2025-07-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cerfa_filler", "0005_alter_beneficiaryorganization_uuid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companies",
            options={
                "permissions": [
                    ("change_validation", "Can change the validation status"),
                    ("send_email", "Can send email"),
                ],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
