# Generated by Django 5.2.4 on 2025-07-31 09:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cerfa_filler", "0006_alter_companies_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclarativeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=15, unique=True, verbose_name="Label"),
                ),
            ],
            options={
                "verbose_name": "Declarative structure",
                "verbose_name_plural": "Declarative structures",
            },
        ),
        migrations.AddField(
            model_name="companies",
            name="cheque_deposit_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Cheque deposit date"
            ),
        ),
        migrations.AddField(
            model_name="companies",
            name="comment",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Comment"
            ),
        ),
        migrations.AddField(
            model_name="companies",
            name="donation_object",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Object"
            ),
        ),
        migrations.AddField(
            model_name="companies",
            name="timestamp_create",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companies",
            name="timestamp_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="beneficiaryorganization",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="companies",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="companies",
            name="declarative_structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cerfa_filler.declarativestructure",
                verbose_name="Declarative structure",
            ),
        ),
    ]
