# Generated by Django 5.2.4 on 2025-07-29 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerfa_filler', '0006_beneficiaryorganization_alter_companies_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryorganization',
            name='additional_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Additional address'),
        ),
        migrations.AddField(
            model_name='beneficiaryorganization',
            name='object_description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Object'),
        ),
        migrations.AddField(
            model_name='companies',
            name='additional_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Additional address'),
        ),
        migrations.AlterField(
            model_name='beneficiaryorganization',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d82f21ee-fc94-4ac7-b5db-96bbd4ffd4f5'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='order',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Order number'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d82f21ee-fc94-4ac7-b5db-96bbd4ffd4f5'), primary_key=True, serialize=False, unique=True),
        ),
    ]
