# Generated by Django 5.2.11 on 2026-02-05 13:39

import multi_email_field.fields
from django.db import migrations

def migrate_emails(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Companies = apps.get_model("cerfa_filler", "Companies")
    for company in Companies.objects.all():
        company.emails = [company.email,]
        company.save()
    BeneficiaryOrganization = apps.get_model("cerfa_filler", "BeneficiaryOrganization")
    for beneficiary in BeneficiaryOrganization.objects.all():
        beneficiary.emails = [beneficiary.email,]
        beneficiary.save()



class Migration(migrations.Migration):

    dependencies = [
        (
            "cerfa_filler",
            "0007_declarativestructure_companies_cheque_deposit_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="declarativestructure",
            options={
                "ordering": ("label",),
                "verbose_name": "Declarative structure",
                "verbose_name_plural": "Declarative structures",
            },
        ),
        migrations.AddField(
            model_name="beneficiaryorganization",
            name="emails",
            field=multi_email_field.fields.MultiEmailField(default=[]),
        ),
        migrations.AddField(
            model_name="companies",
            name="emails",
            field=multi_email_field.fields.MultiEmailField(default=[]),
        ),
        migrations.RunPython(migrate_emails, reverse_code=migrations.RunPython.noop),
        
    ]
