# Generated by Django 5.2.11 on 2026-02-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cerfa_filler", "0008_alter_declarativestructure_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beneficiaryorganization",
            name="email",
        ),
        migrations.RemoveField(
            model_name="companies",
            name="email",
        ),
    ]
