# Generated by Django 5.2.11 on 2026-02-05 14:17

import multi_email_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cerfa_filler", "0009_remove_beneficiaryorganization_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiaryorganization",
            name="emails",
            field=multi_email_field.fields.MultiEmailField(
                blank=True, default=[], null=True
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="emails",
            field=multi_email_field.fields.MultiEmailField(
                blank=True, default=[], null=True
            ),
        ),
    ]
