# Generated by Django 5.2.11 on 2026-02-10 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cerfa_filler", "0010_alter_beneficiaryorganization_emails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiaryorganization",
            name="comment",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Comment"
            ),
        ),
        migrations.AddField(
            model_name="beneficiaryorganization",
            name="timestamp_create",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="beneficiaryorganization",
            name="timestamp_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
