# Generated by Django 5.2.11 on 2026-02-10 09:47

import django.db.models.deletion
import django.utils.timezone
import multi_email_field.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cerfa_filler", "0011_beneficiaryorganization_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateIndividual",
            fields=[
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Comment",
                    ),
                ),
                (
                    "emails",
                    multi_email_field.fields.MultiEmailField(
                        blank=True, default=[], null=True
                    ),
                ),
                (
                    "additional_address",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Additional address",
                    ),
                ),
                (
                    "street_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Street number",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Street",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        max_length=10, verbose_name="Postal code"
                    ),
                ),
                (
                    "municipality",
                    models.CharField(
                        max_length=200, verbose_name="Municipality"
                    ),
                ),
                (
                    "cash_donation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Cash Donation",
                    ),
                ),
                (
                    "cash_payment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Cash", "Cash"),
                            ("Cheque", "Cheque"),
                            ("Bank transfer", "Bank transfer"),
                            ("Other", "Other"),
                        ],
                        null=True,
                        verbose_name="Cash payment type",
                    ),
                ),
                (
                    "cheque_deposit_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Cheque deposit date",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Order number",
                    ),
                ),
                (
                    "donation_object",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Object",
                    ),
                ),
                (
                    "date_start",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Initial donation date",
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="End date"
                    ),
                ),
                (
                    "valid_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Validation date"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=200, verbose_name="First name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="Last name"),
                ),
                (
                    "declarative_structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cerfa_filler.declarativestructure",
                        verbose_name="Declarative structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Individual",
                "verbose_name_plural": "Individuals",
                "permissions": [
                    ("change_validation", "Can change the validation status"),
                    ("send_email", "Can send email"),
                ],
            },
        ),
    ]
