# Generated by Django 5.2.11 on 2026-02-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cerfa_filler", "0012_privateindividual"),
    ]

    operations = [
        migrations.AddField(
            model_name="privateindividual",
            name="donation_nature",
            field=models.CharField(
                choices=[
                    ("Cash", "Nature_donation.Cash"),
                    ("Waiver", "Nature_donation.Waiver_of_fees"),
                ],
                default="Cash",
                verbose_name="Nature donation",
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="cash_payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cash", "Cash"),
                    ("Cheque", "Cheque"),
                    ("CB", "Bank card"),
                    ("Bank transfer", "Bank transfer"),
                    ("Other", "Other"),
                ],
                null=True,
                verbose_name="Cash payment type",
            ),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="cash_payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cash", "Cash"),
                    ("Cheque", "Cheque"),
                    ("CB", "Bank card"),
                    ("Bank transfer", "Bank transfer"),
                    ("Other", "Other"),
                ],
                null=True,
                verbose_name="Cash payment type",
            ),
        ),
    ]
