# Generated by Django 5.2.11 on 2026-02-18 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cerfa_filler", "0013_privateindividual_donation_nature_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="beneficiaryorganization",
            options={
                "verbose_name": "Organisme bénéficiaire",
                "verbose_name_plural": "Organismes bénéficiaires",
            },
        ),
        migrations.AlterModelOptions(
            name="companies",
            options={
                "permissions": [
                    ("change_validation", "Can change the validation status"),
                    ("send_email", "Can send email"),
                ],
                "verbose_name": "Personne morale",
                "verbose_name_plural": "Personnes morales",
            },
        ),
        migrations.AlterModelOptions(
            name="companylegalforms",
            options={
                "ordering": ("label",),
                "verbose_name": "Forme légale",
                "verbose_name_plural": "Formes légales",
            },
        ),
        migrations.AlterModelOptions(
            name="declarativestructure",
            options={
                "ordering": ("label",),
                "verbose_name": "Délégation territoriale",
                "verbose_name_plural": "Délégations territoriales",
            },
        ),
        migrations.AlterModelOptions(
            name="privateindividual",
            options={
                "permissions": [
                    ("change_validation", "Can change the validation status"),
                    ("send_email", "Can send email"),
                ],
                "verbose_name": "Particulier",
                "verbose_name_plural": "Particuliers",
            },
        ),
        migrations.AlterField(
            model_name="beneficiaryorganization",
            name="additional_address",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Complément d'addresse",
            ),
        ),
        migrations.AlterField(
            model_name="beneficiaryorganization",
            name="comment",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Commentaire",
            ),
        ),
        migrations.AlterField(
            model_name="beneficiaryorganization",
            name="label",
            field=models.CharField(max_length=200, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="beneficiaryorganization",
            name="legal_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cerfa_filler.companylegalforms",
                verbose_name="Forme juridique",
            ),
        ),
        migrations.AlterField(
            model_name="beneficiaryorganization",
            name="municipality",
            field=models.CharField(max_length=200, verbose_name="Commune"),
        ),
        migrations.AlterField(
            model_name="beneficiaryorganization",
            name="object_description",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="beneficiaryorganization",
            name="postal_code",
            field=models.CharField(max_length=10, verbose_name="Code postal"),
        ),
        migrations.AlterField(
            model_name="beneficiaryorganization",
            name="repository_code",
            field=models.CharField(max_length=20, verbose_name="SIRET"),
        ),
        migrations.AlterField(
            model_name="beneficiaryorganization",
            name="sign_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="Image de la signature (PNG requis)",
            ),
        ),
        migrations.AlterField(
            model_name="beneficiaryorganization",
            name="street",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Rue"
            ),
        ),
        migrations.AlterField(
            model_name="beneficiaryorganization",
            name="street_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Numéro de rue",
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="additional_address",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Complément d'addresse",
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="cash_donation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Montant du don en numéraire",
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="cash_payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cash", "Espèce"),
                    ("Cheque", "Chèque"),
                    ("CB", "Carte bancaire"),
                    ("Bank transfer", "Virement"),
                    ("Other", "Autre"),
                ],
                null=True,
                verbose_name="Type de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="cheque_deposit_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de dépôt de chèque"
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="comment",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Commentaire",
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="date_end",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date de fin de la donation",
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="date_start",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Date du don ou du début de donation",
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="declarative_structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cerfa_filler.declarativestructure",
                verbose_name="Délégation territoriale",
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="donation_object",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Objet de la donation",
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="inkind_donation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valeur du don en nature",
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="inkind_donation_description",
            field=models.TextField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Description du don en nature",
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="label",
            field=models.CharField(max_length=200, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="companies",
            name="legal_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cerfa_filler.companylegalforms",
                verbose_name="Forme juridique",
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="municipality",
            field=models.CharField(max_length=200, verbose_name="Commune"),
        ),
        migrations.AlterField(
            model_name="companies",
            name="order",
            field=models.IntegerField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Numéro d'ordre",
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="postal_code",
            field=models.CharField(max_length=10, verbose_name="Code postal"),
        ),
        migrations.AlterField(
            model_name="companies",
            name="repository_code",
            field=models.CharField(max_length=20, verbose_name="SIRET"),
        ),
        migrations.AlterField(
            model_name="companies",
            name="street",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Rue"
            ),
        ),
        migrations.AlterField(
            model_name="companies",
            name="street_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Numéro de rue",
            ),
        ),
        migrations.AlterField(
            model_name="companylegalforms",
            name="code",
            field=models.CharField(
                max_length=4, unique=True, verbose_name="Code"
            ),
        ),
        migrations.AlterField(
            model_name="companylegalforms",
            name="label",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="declarativestructure",
            name="label",
            field=models.CharField(
                max_length=15, unique=True, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="additional_address",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Complément d'addresse",
            ),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="cash_donation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Montant du don en numéraire",
            ),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="cash_payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cash", "Espèce"),
                    ("Cheque", "Chèque"),
                    ("CB", "Carte bancaire"),
                    ("Bank transfer", "Virement"),
                    ("Other", "Autre"),
                ],
                null=True,
                verbose_name="Type de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="cheque_deposit_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de dépôt de chèque"
            ),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="comment",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Commentaire",
            ),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="date_end",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date de fin de la donation",
            ),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="date_start",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Date du don ou du début de donation",
            ),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="declarative_structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cerfa_filler.declarativestructure",
                verbose_name="Délégation territoriale",
            ),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="donation_nature",
            field=models.CharField(
                choices=[
                    ("Cash", "Don en numéraire"),
                    ("Waiver", "Abandon de frais"),
                ],
                default="Cash",
                verbose_name="Nature du don",
            ),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="donation_object",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Objet de la donation",
            ),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="first_name",
            field=models.CharField(max_length=200, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="last_name",
            field=models.CharField(max_length=200, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="municipality",
            field=models.CharField(max_length=200, verbose_name="Commune"),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="order",
            field=models.IntegerField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Numéro d'ordre",
            ),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="postal_code",
            field=models.CharField(max_length=10, verbose_name="Code postal"),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="street",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Rue"
            ),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="street_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Numéro de rue",
            ),
        ),
    ]
