# Generated by Django 5.2.11 on 2026-03-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cerfa_filler",
            "0014_alter_beneficiaryorganization_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="companies",
            name="tax_receipt",
            field=models.BooleanField(
                default=True,
                help_text="Souhaite recevoir un reçu fiscal",
                verbose_name="Reçu fiscal",
            ),
        ),
        migrations.AddField(
            model_name="privateindividual",
            name="tax_receipt",
            field=models.BooleanField(
                default=True,
                help_text="Souhaite recevoir un reçu fiscal",
                verbose_name="Reçu fiscal",
            ),
        ),
    ]
