# Generated by Django 5.2.12 on 2026-03-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cerfa_filler",
            "0015_companies_tax_receipt_privateindividual_tax_receipt",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companies",
            name="cheque_deposit_date",
        ),
        migrations.RemoveField(
            model_name="privateindividual",
            name="cheque_deposit_date",
        ),
    ]
