# Generated by Django 5.2.12 on 2026-03-19 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cerfa_filler", "0016_remove_companies_cheque_deposit_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companies",
            name="declarative_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cerfa_filler.declarativestructure",
                verbose_name="Délégation territoriale",
            ),
        ),
        migrations.AlterField(
            model_name="privateindividual",
            name="declarative_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cerfa_filler.declarativestructure",
                verbose_name="Délégation territoriale",
            ),
        ),
    ]
